server:
  port: 8087
  address: 0.0.0.0

spring:
  application:
    name: mh3-backend
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hackathon-db
    username: dbadmin
    password: password

app:
  cors:
    origin: "http://localhost:4200"

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5p ${PID} --- [%15.15t] [%25.25X{traceId:-},%16.16X{spanId:-}] %-40.40logger{39} : %m%n%wEx"
